qcacld-3.0: Properly guard hdd_debugfs_process_mib_stats
This corrects the following compilation error:

../drivers/staging/qcacld-3.0/core/hdd/src/wlan_hdd_stats.c:5605:2: error: implicit declaration of function 'hdd_debugfs_process_mib_stats' [-Werror,-Wimplicit-function-declaration]
        hdd_debugfs_process_mib_stats(adapter, stats);
        ^

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>
(cherry picked from commit 43a148d193ff9aa7634e33b4316e7eef847d00cd)
(cherry picked from commit b0fb740eef45f282373fb8bdbb5592a30cafdcb6)